### ISSUE TITLE
Publish latest to NPM

### ISSUE THREAD

**Issue by timt** [kevinstumpf/react-native-signature-pad#39]
Hi, 

I see you merged the proptypes pull request from latitude-digital, but it doesn't look like you have bumped the version and released to npm?

Can you release the latest to npm?

**Comment by kevinstumpf** [comment]
Just invited you as a collaborator to the project -- that should allow you to publish to npm

**Comment by timt** [comment]
thanks

**Comment by timt** [comment]
Hi Kevin,

I will need permission on to publish to the library to npmjs as well to be able to do this 

https://www.npmjs.com/package/react-native-signature-pad

**Comment by kevinstumpf** [comment]
done
ᐧ

**Comment by ReneDH** [comment]
Hello,
How can I see, if the publish to npm is done? You are cerated a new version number?

Thanks
Rene

**Comment by timt** [comment]
@kevinstumpf Thanks, I still can't publish to NPM, my NPM registry details are:
email - ttennant@gmail.com 
username - timtennant

**Comment by kevinstumpf** [comment]
Done - can you pls try again?
ᐧ

**Comment by timt** [comment]
Perfect that worked. I have now published the latest as 0.0.9
